// Copyright 2018 Copyright AcceleCom Inc.
// DO NOT EDIT. This file (and "version") is generated by CMake.
// Run CMake configure step to update it.
#ifndef INCLUDE_FAIR_VERSION_H_
#define INCLUDE_FAIR_VERSION_H_

#define FAIRCPP_VERSION_STRING "2.0.150"
#define FAIRCPP_VERSION_MAJOR 2
#define FAIRCPP_VERSION_MINOR 0
#define FAIRCPP_VERSION_PATCH 150
#define FAIRCPP_VERSION_QUALIFIER
#define FAIRCPP_VERSION_HEXA \
          ((FAIRCPP_VERSION_MAJOR << 24) | \
          (FAIRCPP_VERSION_MINOR << 16) | (FAIRCPP_VERSION_PATCH << 8))

#endif  // INCLUDE_FAIR_VERSION_H_
